### ISSUE TITLE
Consider supporting PyPI ecosystem?

### ISSUE THREAD

**Issue by aswinnnn** [psastras/sbom-rs#109]
I admit this is a stretch but I wanted to ask anyway.
I have a project that uses OSV to scan python dependencies, currently limited to parsing from requirements.txt, pyproject.toml and the likes.
I figure SBOMs are the more professional way to deal with dependencies and would like to allow parsing and exporting it, but no one seems to have done something for the Python environment in rust yet, not that I know of. (My end goal is to make a security toolkit, and SBOMs are crucial.)
I figure I might ask you instead of making one from scratch, I apologize if it comes off as ignorant since your work mainly focuses on cargo. Looking forward to this project btw.

**Comment by psastras** [comment]
@aswinnnn no problem with asking. at this point in time though I am not interested in adding support for the Python ecosystem. 

personally if i were to write an sbom generator for a python ecosystem, i would most likely choose Python, as the support for parsing and understanding the various dependency standards is just generally better in the native language -- but I think there are a lot of available tools already in the python ecosystem.

**Comment by aswinnnn** [comment]
ah, I see. That's a dealbreaker for me since my initial project is in rust and i'd like to continue that way. Thanks for the reply.
