### ISSUE TITLE
Questions About Expanding Use Case

### ISSUE THREAD

**Issue by zicklag** [psastras/sbom-rs#85]
Hey there!

I've got a project I'm working on and I've really run into the need for a way create appropriate attribution for all of the dependencies that I'm using, which include both PNPM and Cargo dependencies.

As far as Cargo dependencies, it looks like this crate does a lot of what I need, but in order to comply with the license terms, I need to be able to include actual copyright texts and, in some cases, such as MIT, the entire license text in the attribution.

My question is what are you open to expanding on in `cargo sbom`. Would you be open to a way to search out the license text along with the crates when possible, by reading, for example, the `license_file` field of cargo packages and scanning the files for copyright notices?

I'm not expecting that you want to bother supporting NPM at this point, and that's fine, I'd just need to make/find a separate tool for NPM packages and make a tool for combining the two SBOMs.

Anyway, I'm really still looking around and experimenting and trying to find the easiest thing that I can get working to satisfy the license requirements, so any thoughts are helpful! I don't want to spend time designing a solution right now if I don't have to, but if there's no other option, then I may have to. :)

---

**Edit:** It looks like `cargo about` captures all the information I need, I just have to supplement it. That means it might be the easiest route for me for now, but I'm still curious if you have any thoughts on expanding this, because I do like that you're already using SPDX.

**Comment by psastras** [comment]
@zicklag Thanks for taking the time to do some research and write this out; in principle I think it's a good idea and it was something I considered; the main limiting factor being that AFAIK by default `cargo` doesn't provide the full license text of its dependencies in the lockfile or any project metadata. This means that an implementation of this would have to supplement the data by doing internet lookups based on the local metadata (and I believe that this is what `cargo about` does based on a quick glance).

There's nothing stopping us from doing this, except that it's a very different code path and also removes the nice self contained CLI that can just read what's already in any standard `cargo` project. What this all means is that I think it's nice to have, and would probably put it as an opt in feature (ex. behind a flag like --download-licenses), but probably needs some time investment to implement this.

More generally I think this high level idea could be use to supplement other data (like security vulnerabilities behind a --download-vulnerability-info flag).

**Comment by zicklag** [comment]
Thanks for the response!

I've done some more research and looked more carefully at the license obligations for the common Open Source licenses that I've found in my project:

https://gist.github.com/zicklag/9d70d481dd826a74a6adc2a8c5605772

TL;DR my ( NOT LEGAL ADVICE ) evaluation is that one proper attribution form would be an HTML file containing:
- A table with a row for every dependency and the following columns: Name, Package URL, License ID, Notices ( containing all copyrights, authors, and notices found by scanning the package source and metadata )
- A list of the official license texts from the SPDX license list for all of the licenses used.

I'm going to have to produce this attribution from my Cargo and PNPM monorepo, and I think I've decided I'm just going to try and write the simplest tool that I can that will do that and see how it goes.

> This means that an implementation of this would have to supplement the data by doing internet lookups based on the local metadata

I think this could be done with local lookups, assuming you ran a `cargo check` and `pnpm install` first.

The datadog license tool, which is actually the closest thing to what I need so far, does this I think:

https://github.com/DataDog/rust-license-tool/blob/6a37a4c6318b8ffcc21973d0178bc8cdc461b43d/src/main.rs#L435

Anyway I'll have whatever code I end up with Unlicensed if you want to do something similar here. I think I don't end up needing a full SBOM at this point, but we'll see where I end up.

**Comment by Shnatsel** [comment]
@zicklag I believe you are looking for https://github.com/EmbarkStudios/cargo-about

**Comment by zicklag** [comment]
In case anybody is interested, I ended up with a very small project that serves my needs. I think I'll just continue and expand on that for whatever I need in the future.

https://github.com/katharostech/make-notices

Since I'm setup now, I'm closing the issue, but feel free to re-open if you think this is something that will still want to be left open for the future.
